# NOTEBOOK SETTINGS
[notebook]
dir = "~/notes"

# NOTE SETTINGS
[note]
filename = "{{id}}-{{slug title}}"

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# EXTRA VARIABLES
[extra]
author = "D.Mayb"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"


# COMMAND ALIASES
[alias]

# Edit the last modified note.
edi = "zk edit --interactive"

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

# Add a new book
newbook = "zk new books --group book --title $1 --extra author=$2,link=$3"

[group.book]
paths = [ "books" ]

[group.book.note]
filename = "{{id}}-{{slug title}}"
template = "book.md"

