[accounts.google]

# Make this current account the default one to use when no account is
# specified in the CLI with the --account argument.
#
default = true

# The client credentials
client-id = "638381403946-80ft44hhqlknfsng6d8uk57l2ojb6ftj.apps.googleusercontent.com"
client-secret.command = "mimosa password show google"

# Endpoints, given by your OAuth provider.
#
endpoints.authorization = "https://accounts.google.com/o/oauth2/auth?access_type=offline"
endpoints.token = "https://www.googleapis.com/oauth2/v3/token"
#endpoints.redirection = "http://localhost"

# Access token scopes
#
scopes = [
  "https://www.googleapis.com/auth/gmail.modify",
  "https://www.googleapis.com/auth/calendar.events",
  "https://www.googleapis.com/auth/drive.readonly"
  ]

# TLS configuration
#
#tls = "native-tls"
#tls = "rustls-aws"
#tls = "rustls-ring"

# Enables Proof Key for Code Exchange (rfc7636)
pkce = true

# Automatically refreshes expired access token when using `ortie token show` command.
auto-refresh = true

# Token storage
storage.read.command = ["mimosa", "password", "show", "google-access-token"]
storage.write.command = ["mimosa", "password", "write", "google-access-token"]
