require('plugins.nvim')
require('plugins.oil')
require('plugins.colors')
require('plugins.whichkey')
require('plugins.lsp')
require('plugins.text')
require('plugins.email')
require('plugins.experiments')
